const quotes = [
    { text: "", author: "", heading: "" },
    { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", heading: "Life and Inspiration" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", heading: "Life and Inspiration" },
    { text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs", heading: "Life and Inspiration" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", heading: "Life and Inspiration" },
    { text: "Believe you can, and you're halfway there.", author: "Theodore Roosevelt", heading: "Life and Inspiration" },
    { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Wlt Whitman", heading: "Life and Inspiration" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker", heading: "Life and Inspiration" },
    { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albrt Schweitzer", heading: "Life and Inspiration" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", heading: "Life and Inspiration" },
    { text: "Every day is a second chance.", author: "Unknown", heading: "Life and Inspiration" },
    { text: "Love is not about how much you say 'I love you,' but how much you prove that it’s true.", author: "Unknown", heading: "Love and Relationships" },
    { text: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn", heading: "Love and Relationships" },
    { text: "Where there is love, there is life.", author: "Mahatma Gandhi", heading: "Love and Relationships" },
    { text: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle", heading: "Love and Relationships" },
    { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott", heading: "Love and Relationships" },
    { text: "A loving heart is the truest wisdom.", author: "Charles Dickens", heading: "Love and Relationships" },
    { text: "The greatest thing you’ll ever learn is just to love and be loved in return.", author: "Eden Ahbez", heading: "Love and Relationships" },
    { text: "In dreams and in love, there are no impossibilities.", author: "János Arany", heading: "Love and Relationships" },
    { text: "You come to love not by finding the perfect person, but by seeing an imperfect person perfectly.", author: "Sam Keen", heading: "Love and Relationships" },
    { text: "True love begins when nothing is looked for in return.", author: "Antoine de Saint-Exupéry", heading: "Love and Relationships" },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", heading: "Wisdom and Knowledge" },
    { text: "Wisdom begins in wonder.", author: "Socrates", heading: "Wisdom and Knowledge" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", heading: "Wisdom and Knowledge" },
    { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", heading: "Wisdom and Knowledge" },
    { text: "Education is the most powerful weapon you can use to change the world.", author: "Nelson Mandela", heading: "Wisdom and Knowledge" },
    { text: "It is not the answer that enlightens, but the question.", author: "Eugene Ionesco", heading: "Wisdom and Knowledge" },
    { text: "Wisdom is the reward you get for a lifetime of listening when you would rather have talked.", author: "Mark Twain", heading: "Wisdom and Knowledge" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", heading: "Wisdom and Knowledge" },
    { text: "The eye sees only what the mind is prepared to comprehend.", author: "Robertson Davies", heading: "Wisdom and Knowledge" },
    { text: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix", heading: "Wisdom and Knowledge" },
    { text: "Hope is being able to see that there is light despite all of the darkness.", author: "Desmond Tutu", heading: "Hope and Positivity" },
    { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt", heading: "Hope and Positivity" },
    { text: "Optimism is the faith that leads to achievement.", author: "Helen Keller", heading: "Hope and Positivity" },
    { text: "Once you choose hope, anything’s possible.", author: "Christopher Reeve", heading: "Hope and Positivity" },
    { text: "Every sunset is an opportunity to reset. Every sunrise begins with new eyes.", author: "Richie Norton", heading: "Hope and Positivity" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", heading: "Hope and Positivity" },
    { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt", heading: "Hope and Positivity" },
    { text: "Happiness can be found, even in the darkest of times, if one only remembers to turn on the light.", author: "J.K. Rowling", heading: "Hope and Positivity" },
    { text: "Courage is found in unlikely places.", author: "J.R.R. Tolkien", heading: "Hope and Positivity" },
    { text: "No matter how hard the past, you can always begin again.", author: "Buddha", heading: "Hope and Positivity" },
    { text: "Success is not final; failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill", heading: "Motivation and Success" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan", heading: "Motivation and Success" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James", heading: "Motivation and Success" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", heading: "Motivation and Success" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson", heading: "Motivation and Success" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", heading: "Motivation and Success" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller", heading: "Motivation and Success" },
    { text: "I never dreamed about success. I worked for it.", author: "Estée Lauder", heading: "Motivation and Success" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", heading: "Motivation and Success" },
    { text: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknow", heading: "Motivation and Success" },
    { text: "Happiness is not something ready-made. It comes from your own actions.", author: "  Dalai Lama", heading: "Happiness and Peace" },
    { text: "The purpose of our lives is to be happy.", author: "  Dalai Lama", heading: "Happiness and Peace" },
    { text: "Happiness depends upon ourselves.", author: "  Aristotle", heading: "Happiness and Peace" },
    { text: "Do more of what makes you happy.", author: "  Unknown", heading: "Happiness and Peace" },
    { text: "There is no path to happiness; happiness is the path.", author: "  Buddha", heading: "Happiness and Peace" },
    { text: "Peace begins with a smile.", author: "  Mother Teresa", heading: "Happiness and Peace" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "  Mahatma Gandhi", heading: "Happiness and Peace" },
    { text: "Count your age by friends, not years. Count your life by smiles, not tears.", author: "  John Lennon", heading: "Happiness and Peace" },
    { text: "A calm mind brings inner strength and self-confidence, so that’s very important for good health.", author: "  Dalai Lama", heading: "Happiness and Peace" },
    { text: "Happiness radiates like the fragrance from a flower and draws all good things toward you.", author: "  Maharishi Mahesh Yogi", heading: "Happiness and Peace" },
    { text: "All our dreams can come true if we have the courage to pursue them.", author: "  Walt Disney", heading: "Dreams and Ambitions" },
    { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "  Henry David Thoreau", heading: "Dreams and Ambitions" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "  Eleanor Roosevelt", heading: "Dreams and Ambitions" },
    { text: "Dream as if you’ll live forever. Live as if you’ll die today.", author: "  James Dean", heading: "Dreams and Ambitions" },
    { text: "Shoot for the moon. Even if you miss, you’ll land among the stars.", author: "  Norman Vincent Peale", heading: "Dreams and Ambitions" },
    { text: "Dream big dreams. Small dreams have no magic.", author: "  Dottie Boreyko", heading: "Dreams and Ambitions" },
    { text: "Without dreams, there can be no courage. And without courage, there can be no action.", author: "  Wim Wenders", heading: "Dreams and Ambitions" },
    { text: "Every great dream begins with a dreamer.", author: "  Harriet Tubman", heading: "Dreams and Ambitions" },
    { text: "The best way to make your dreams come true is to wake up.", author: "  Paul Valéry", heading: "Dreams and Ambitions" },
    { text: "A dream doesn’t become reality through magic; it takes sweat, determination, and hard work.", author: "  Colin Powell", heading: "Dreams and Ambitions" },
    { text: "That which does not kill us makes us stronger.", author: "  Friedrich Nietzsche", heading: "Strength and Resilience" },
    { text: "It always seems impossible until it’s done.", author: "  Nelson Mandela", heading: "Strength and Resilience" },
    { text: "Fall seven times, stand up eight.", author: "  Japanese Proverb", heading: "Strength and Resilience" },
    { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "  Mahatma Gandhi", heading: "Strength and Resilience" },
    { text: "The world breaks everyone, and afterward, many are strong at the broken places.", author: "  Ernest Hemingway", heading: "Strength and Resilience" },
    { text: "When you come out of the storm, you won’t be the same person who walked in. That’s what the storm is all about.", author: "  Haruki Murakami", heading: "Strength and Resilience" },
    { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "  Bruce Lee", heading: "Strength and Resilience" },
    { text: "Strength grows in the moments when you think you can’t go on, but you keep going anyway.", author: "  Unknown", heading: "Strength and Resilience" },
    { text: "Life doesn’t get easier or more forgiving; we get stronger and more resilient.", author: "  Steve Maraboli", heading: "Strength and Resilience" },
    { text: "Courage isn’t having the strength to go on—it is going on when you don’t have strength.", author: "  Napoleon Bonaparte", heading: "Strength and Resilience" },
    { text: "Be the change that you wish to see in the world.", author: "  Mahatma Gandhi", heading: "Change and Growth" },
    { text: "Change is the only constant in life.", author: "  Heraclitus", heading: "Change and Growth" },
    { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "  George Bernard Shaw", heading: "Change and Growth" },
    { text: "Without continual growth and progress, such words as improvement, achievement, and success have no meaning.", author: "  Benjamin Franklin", heading: "Change and Growth" },
    { text: "Don’t be afraid of change. You may lose something good, but you may gain something better.", author: "  Unknown", heading: "Change and Growth" },
    { text: "Life is either a daring adventure or nothing at all.", author: "  Helen Keller", heading: "Change and Growth" },
    { text: "If you don’t like something, change it. If you can’t change it, change your attitude.", author: "  Maya Angelou", heading: "Change and Growth" },
    { text: "Your life does not get better by chance; it gets better by change.", author: "  Jim Rohn", heading: "Change and Growth" },
    { text: "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don’t belong.", author: "  Mandy Hale", heading: "Change and Growth" },
    { text: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.", author: "  Maya Angelou", heading: "Change and Growth" },
    { text: "No act of kindness, no matter how small, is ever wasted.", author: "  Aesop", heading: "Kindness and Compassion"},
    { text: "Kindness is the language which the deaf can hear and the blind can see.", author: "  Mark Twain", heading: "Kindness and Compassion"},
    { text: "You cannot do a kindness too soon, for you never know how soon it will be too late.", author: "  Ralph Waldo Emerson", heading: "Kindness and Compassion"},
    { text: "A warm smile is the universal language of kindness.", author: "  William Arthur Ward", heading: "Kindness and Compassion"},
    { text: "Carry out a random act of kindness, with no expectation of reward.", author: "  Princess Diana", heading: "Kindness and Compassion"},
    { text: "Be kind whenever possible. It is always possible.", author: "  Dalai Lama", heading: "Kindness and Compassion"},
    { text: "One kind word can change someone’s entire day.", author: "  Unknown", heading: "Kindness and Compassion"},
    { text: "Compassion and tolerance are not a sign of weakness, but a sign of strength.", author: "  Dalai Lama", heading: "Kindness and Compassion"},
    { text: "Do things for people not because of who they are or what they do in return, but because of who you are.", author: "  Harold S. Kushner", heading: "Kindness and Compassion"},
    { text: "Kindness begins with the understanding that we all struggle.", author: "Charles Glassman", heading:"Kindness and Compassion"},

];

const quoteElement = document.getElementById('quote');
const authorElement = document.getElementById('author');
const headingElement = document.getElementById('heading');
const generateBtn = document.getElementById('generateBtn');

generateBtn.addEventListener('click', () => {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];
    headingElement.textContent = `"${randomQuote.heading}"`;
    quoteElement.textContent = `"${randomQuote.text}"`;
    authorElement.textContent = `- ${randomQuote.author}`;
});